; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx900 < %s | FileCheck %s

define amdgpu_kernel void @local_to_flat(ptr addrspace(3) %ptr) {
; CHECK-LABEL: local_to_flat:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_load_dword s2, s[4:5], 0x0
; CHECK-NEXT:    s_mov_b64 s[0:1], src_shared_base
; CHECK-NEXT:    v_mov_b32_e32 v2, 7
; CHECK-NEXT:    s_waitcnt lgkmcnt(0)
; CHECK-NEXT:    s_cmp_lg_u32 s2, -1
; CHECK-NEXT:    s_cselect_b32 s0, s1, 0
; CHECK-NEXT:    s_cselect_b32 s1, s2, 0
; CHECK-NEXT:    v_mov_b32_e32 v0, s1
; CHECK-NEXT:    v_mov_b32_e32 v1, s0
; CHECK-NEXT:    flat_store_dword v[0:1], v2
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    s_endpgm
  %x = addrspacecast ptr addrspace(3) %ptr to ptr, !nonnull !{}
  store volatile i32 7, ptr %x
  ret void
}

define amdgpu_kernel void @flat_to_local(ptr %ptr) {
; CHECK-LABEL: flat_to_local:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; CHECK-NEXT:    v_mov_b32_e32 v0, 7
; CHECK-NEXT:    s_waitcnt lgkmcnt(0)
; CHECK-NEXT:    s_cmp_lg_u64 s[0:1], 0
; CHECK-NEXT:    s_cselect_b32 s0, s0, -1
; CHECK-NEXT:    v_mov_b32_e32 v1, s0
; CHECK-NEXT:    ds_write_b32 v1, v0
; CHECK-NEXT:    s_endpgm
  %x = addrspacecast ptr %ptr to ptr addrspace(3), !nonnull !{}
  store volatile i32 7, ptr addrspace(3) %x
  ret void
}
